 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: foobar
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: foobar
     spec:
       containers:
         - name: foobar
           image: quay.io/metral/k8s-demo:0.0.1
           imagePullPolicy: Always
           ports:
             - name: http
               containerPort: 8888
